- app/com/arpnetworking/metrics/portal/alerts/impl/DatabaseAlertRepository.java
- app/com/arpnetworking/metrics/portal/expressions/impl/DatabaseExpressionRepository.java
- app/com/arpnetworking/metrics/portal/hosts/impl/DatabaseHostRepository.java
Since 'created' is past tense and technically the new object has yet to be created when 'created' is set to 'true', I think using "isNew[...]" as a variable name is easier to understand in this context.
> modified: a boolean 'created' variable

- public/html/GraphViewModel.html
Make the config modal a sibling of the sortable graph instead of a child.  This makes it so that the draggable handle is below the modal.
> Fix dragging graphs under config dialog

- app/assets/javascripts/start_app.ts
> Assert typeahead's dependency on jquery in RequireJS config.

- app/assets/javascripts/classes/MetricNodeVM.ts
- app/assets/javascripts/classes/MetricsBrowseList.ts
- public/html/GraphViewModel.html
... so that when you hover over a metric in the tree, you see the full metric name.
> GUI: Add a tooltip to the metric with the full metric name.

- app/controllers/ProxyController.java
- project/Build.scala
- project/plugins.sbt
Switched Findbugs plugins to https://github.com/JosephEarl/sbt-findbugs and enabled fail on error.
This addresses #30.
```
[ville:metrics-portal (master|✚2)]$ ./activator findbugs
[info] Loading project definition from /Users/ville/Workspace/ArpNetworking/metrics-portal/project
[info] Compiling 1 Scala source to /Users/ville/Workspace/ArpNetworking/metrics-portal/project/target/scala-2.10/sbt-0.13/classes...
[info] Set current project to metrics-portal (in build file:/Users/ville/Workspace/ArpNetworking/metrics-portal/)
[error] Warnings generated: 1
[error] SIC_INNER_SHOULD_BE_STATIC_ANON found in controllers/ProxyController.java:67: priority 3 category PERFORMANCE
[error] Class controllers.ProxyController$1 found in controllers/ProxyController.java:67-72
[error] 1 issue(s) found in …
```
> Findbugs Fail on Error

- app/com/arpnetworking/metrics/portal/hosts/impl/ForemanClient.java
- test/com/arpnetworking/metrics/portal/hosts/impl/ForemanClientTest.java
- test/resources/com/arpnetworking/metrics/portal/hosts/impl/foreman_v1.8_hosts_response.json
Foreman version 1.8 -- and possibly others -- return a simple list of host objects. This change adds support for that format if the root json node is a list and not an object.
> Foreman 1.8 Support in Host Provider

- app/com/arpnetworking/metrics/portal/hosts/impl/DatabaseHostRepository.java
Improved postgresql full-text autocomplete. This treats spaces as search token separators and looks for to match all tokens or all token prefixes. The tokenization was also updated to include priority: first, the full hostname; second, the 'lablels' (separated by '.'); third, the 'words' (separated by '-'); finally, any alpha-numeric tokens. The results on my sample data are better prefix matching, and improved targetting during multi-token searches.
PS. @BrandonArp can you take a look at: https://github.com/ArpNetworking/metrics-portal/issues/74
> Improve Postgresql Autocomplete

- app/com/arpnetworking/metrics/portal/scheduling/Schedule.java
- app/com/arpnetworking/metrics/portal/scheduling/impl/BaseSchedule.java
- app/com/arpnetworking/metrics/portal/scheduling/impl/NeverSchedule.java
- app/com/arpnetworking/metrics/portal/scheduling/impl/OneOffSchedule.java
- app/com/arpnetworking/metrics/portal/scheduling/impl/PeriodicSchedule.java
- test/com/arpnetworking/metrics/portal/scheduling/impl/BaseScheduleTest.java
- test/com/arpnetworking/metrics/portal/scheduling/impl/NeverScheduleTest.java
- test/com/arpnetworking/metrics/portal/scheduling/impl/OneOffScheduleTest.java
- test/com/arpnetworking/metrics/portal/scheduling/impl/PeriodicScheduleTest.java
- bugfix in how PeriodicSchedule interacts with DST switchovers (and add tests for such cases)
- prefer `Instant` to `ZonedDateTime` ~everywhere; PeriodicSchedule still uses zones, but the `Schedule` interface now uses plain `Instant`s, because Schedules should have the option to not care about time zones.
> Schedule fixups

- app/com/arpnetworking/rollups/MetricsDiscovery.java
- app/global/MainModule.java
- app/models/internal/Features.java
- app/models/internal/impl/DefaultFeatures.java
- conf/cluster.conf
- conf/portal.application.conf
- test/com/arpnetworking/rollups/MetricsDiscoveryTest.java
I added regex based whitelist/blacklist support.  The behavior is that if a metric isn't in either list then it is accepted, if it's in the blacklist then it is filtered out unless it is also found in the whitelist.
I also add 'rollups' as a feature in the configuration and provided a default configuration.
> Added rollup metric name filtering, add default configuration and made rollups a feature.

- app/com/arpnetworking/metrics/portal/reports/ReportQuery.java
- app/com/arpnetworking/metrics/portal/reports/ReportRepository.java
- app/com/arpnetworking/metrics/portal/reports/impl/DatabaseReportRepository.java
- app/com/arpnetworking/metrics/portal/reports/impl/NoReportRepository.java
- app/com/arpnetworking/metrics/portal/scheduling/JobRepository.java
- app/models/internal/impl/DefaultJobQuery.java
- app/models/internal/impl/DefaultQueryResult.java
- app/models/internal/impl/DefaultReportQuery.java
- test/com/arpnetworking/metrics/portal/reports/impl/DatabaseReportRepositoryTest.java
The current API only allows for querying for the Reports as Jobs.
`ReportRepository#queryReports` can be used to retrieve the Report instances directly (e.g. for controller pagination). This doesn't require much of an implementation change since we can add a default for `ReportRepository#query` that just wraps `queryReport`.
Alternatively, I could have used wildcard types in JobRepository, but this ends up polluting client-side code and the query result types with wildcards themselves.
> Refine the ReportRepository API to allow for querying Reports

- app/com/arpnetworking/metrics/portal/reports/impl/DatabaseReportRepository.java
- test/com/arpnetworking/metrics/portal/reports/impl/DatabaseReportRepositoryTest.java
The query result should contain the total count of *all* rows, not just the ones within the current page.
Most of these changes are modifying existing tests to catch the bug, since the change itself was only a few lines.
> Fix incorrect row total in DatabaseReportRepository#query

- app/com/arpnetworking/metrics/portal/scheduling/JobExecutorActor.java
Currently, `JobExecutorActor` uses the system dispatcher to pipe its job's execution's output back to itself (the executor). It should probably use its own dispatcher.
> Fix job executor dispatching

- app/com/arpnetworking/rollups/RollupGenerator.java
- test/com/arpnetworking/rollups/RollupGeneratorTest.java
When working on the Kairos tools (https://github.com/ddimensia/kairos_tools) for copying metrics data I noticed that the SaveAs aggregator name and parameters were incorrect in the Metrics Portal RollupGenerator.  They should be name = 'save_as' and the parameter for the destination metric name should be 'metric_name'.
> Fixed incorrect aggregator name and paramter for SaveAs aggregator.

- conf/postgresql.application.conf
Configure the Akka JDBC Slick configuration using the common `postgres.*` variables the same as the Play/Ebean DB server default configuration.
> Improve Slick DB Config

- .gitignore
- app/assets/javascripts/classes/KnockoutBindings.ts
- app/assets/javascripts/classes/PaginatedSearchableList.ts
- app/assets/javascripts/classes/alerts/AlertsViewModel.ts
- app/assets/javascripts/classes/hostregistry/HostRegistryViewModel.ts
- app/assets/javascripts/classes/reports/EditReportViewModel.ts
- app/assets/javascripts/classes/reports/Models.ts
- app/assets/javascripts/classes/reports/Report.ts
- app/assets/javascripts/classes/reports/ReportsViewModel.ts
- public/html/alerts/AlertsViewModel.html
- public/html/components/Pager.html
- public/html/hostregistry/HostRegistryViewModel.html
- public/html/reports/EditReportViewModel.html
- public/html/reports/EditScheduleViewModel.html
- public/html/reports/ReportsViewModel.html
- public/stylesheets/main.css
Adds a paginated list view for the reports page, and factors out shared `Base*ViewModel` types from both the `EditReportViewModel` and `ReportViewModel`.
~An open problem is how to unify the html template with the pager from `AlertsViewModel`. The durandal components were incompatible because of how the template is structured; this has several templatized portions while `AlertsViewModel` has only one. I had attempted to extract out the entity-agnostic functionality but due to the way durandal binds components after the DOM is created, `<tr>` elements seem to disappear or get hoisted upwards since they are not yet enclosed in a `<table>`.~
UPDATE: In somewhat of a hack, I was able to include the new paging template after all by embedding the row elements into a temporary table that is only …
> Report list view frontend

- app/com/arpnetworking/kairos/client/KairosDbClientImpl.java
- app/com/arpnetworking/kairos/client/KairosDbRequestException.java
Convert the `KairosDbRequestException` exception type to use Java's URI instead of Akka's URI to improve encapsulation of Akka in Metrics Portal as well as to improve serialization of the exception since Jackson natively supports Java URI encoding but does not support Akka URI encoding with Steno. This was not apparent in testing because KeyValueEncoder (used in testing) forces all values output with `toString()`. However, it was obvious in prod. Here is some test output when forced to use the production encoder configuration.
With Akka URI:
```
{"time":"2019-05-15T15:47:52.763Z","name":"log","level":"warn","data":{"message":"TEST 1","url":{"_id":"dc79225","_class":"akka.http.impl.model.JavaUri"}},"context":{"host":"vkoskela-mbp.corp.dropbox.com","processId":"49857","threadId":"main","logg …
```
> Switch KairosDbRequestException to Java URI

- app/com/arpnetworking/rollups/MetricsDiscovery.java
- test/java/com/arpnetworking/rollups/MetricsDiscoveryTest.java
Please validate that the unit tests describe the desired behavior. It makes logical sense to me at first pass, but I may have missed something.
Before the change the unit tests would fail with this:
```
java.lang.AssertionError: 
Expected :[web_perf/foo]
Actual   :[web_perf/foo, desktop/bar, mobile/abc]
<Click to see difference>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:144)
at com.arpnetworking.rollups.MetricsDiscoveryTest.testFilterMetricNames(MetricsDiscoveryTest.java:223)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at …
```
> Fix filtering logic and add unit tests.

- app/com/arpnetworking/commons/jackson/databind/module/akka/ActorRefDeserializer.java
- app/com/arpnetworking/commons/jackson/databind/module/akka/ActorRefLoggingSerializer.java
- app/com/arpnetworking/commons/jackson/databind/module/akka/ActorRefSerializer.java
- app/com/arpnetworking/commons/jackson/databind/module/akka/AkkaLoggingModule.java
- app/com/arpnetworking/commons/jackson/databind/module/akka/AkkaModule.java
- app/com/arpnetworking/commons/jackson/databind/module/akka/package-info.java
- app/controllers/MetaController.java
- app/global/MainModule.java
- main/config/logback-console.xml
- main/config/logback.xml
- test/java/com/arpnetworking/commons/jackson/databind/module/package-info.java
`/status` now includes:
```
"allocations": [
{
"incomingShards": {
"count": 0
},
"outgoingShards": {
"count": 0
},
"shardRegion": "akka.tcp://mportal@127.0.0.1:2558/system/sharding/JobExecutor",
"currentShards": {
"count": 0
},
"host": "localhost"
}
],
```
> Add sharding support to status cache.

- app/com/arpnetworking/rollups/RollupGenerator.java
- test/java/com/arpnetworking/rollups/RollupGeneratorTest.java
- test/java/com/arpnetworking/rollups/RollupPeriodTest.java
There was an issue with rollups generating data for the next period due to the fact that endTime is inclusive for KairosDB. 
To fix this I did two things, first I exclude any future data points for the 'LastDatapoint' query by adding an endtime.  Second, I subtract one millisecond from the rollup query endtime so that we don't accidentally save a rollup for an incomplete period...
> Fixed endTime inclusivity issue with rollup queries.

- app/com/arpnetworking/metrics/portal/reports/ReportExecutionContext.java
- app/models/internal/impl/HtmlReportFormat.java
- app/models/internal/impl/PdfReportFormat.java
- app/models/internal/reports/ReportFormat.java
- test/java/com/arpnetworking/metrics/portal/reports/ReportExecutionContextTest.java
Pros: avoiding string typing.
(Arguable) Cons: now must be very picky about string representations of media types (e.g. `text/html; charset=utf-8` instead of merely `text/html`).
I opine that that "con" isn't much of a con: HTML is a way of parsing _strings_, not _bytes_, and I'm actually kind of happy that this change forces greater specificity of how our content is byte-encoded.
> for ReportFormat#getMimeType, use real MediaType class instead of strings

- app/com/arpnetworking/metrics/portal/reports/RenderedReport.java
- app/com/arpnetworking/metrics/portal/reports/Renderer.java
- app/com/arpnetworking/metrics/portal/reports/ReportExecutionContext.java
- app/com/arpnetworking/metrics/portal/reports/impl/chrome/BaseScreenshotRenderer.java
- app/models/internal/impl/DefaultRenderedReport.java
- test/java/com/arpnetworking/metrics/portal/reports/EmailSenderTest.java
- test/java/com/arpnetworking/metrics/portal/reports/ReportExecutionContextTest.java
This avoids forcing every implementation to contain the boilerplate `new DefaultRenderedReport.Builder().setFormat(format).setGeneratedAt(Instant.now()).setScheduledFor(scheduled)`.
Implemented by:
- moving `DefaultRenderedReport.Builder` to `RenderedReport.Builder`
- add `RenderedReport.Builder` argument to `Renderer#render`
- dependency-injecting a `Clock` into `ReportExecutionContext` since it now needs to be able to compute `now()`
> have Renderer populate a builder rather than returning a full RenderedReport

- app/com/arpnetworking/metrics/portal/reports/impl/EmailSender.java
- test/java/com/arpnetworking/metrics/portal/reports/impl/EmailSenderTest.java
- test/java/com/arpnetworking/metrics/portal/reports/impl/package-info.java
I'm not sure how the email branch was green in CI -- after its merge, master has build errors.
`EmailSender` needs to have a `Mailer` dependency-injected into it, or else running the tests will try to make real-life SMTP connections. I've made it a lazily instantiated Mailer in order to avoid making connections before any reports actually need sending.
> make EmailSender take lazily instantiated Mailer

- app/com/arpnetworking/rollups/RollupGenerator.java
- test/java/com/arpnetworking/rollups/RollupGeneratorTest.java
The rollups were having their datapoints snapped to the end of the time period.  This is inconsistent with grafana's default to have the datapoint snapped to the start of the period.  I switched to using alignStartTime to fix the inconsistency.
> Make rollup value snap to the start of the period rather than end.

- app/com/arpnetworking/rollups/RollupGenerator.java
- app/com/arpnetworking/rollups/RollupPeriod.java
- test/java/com/arpnetworking/rollups/RollupGeneratorTest.java
This addresses a few issues with rollups:
1. Backfills could be expensive because multiple periods would try to be rolled up in a single saveas query.  This was addressed by chunking the saveAs queries into one query per period.
2. When the saveAs was moved to save data at the startTime there was a mismatch with how the calculations were made to determine if a rollup needed to occur.  Previously we checked against the end of the most recently closed period, now we check against the start of the most recently closed period.
3. The saveAs query could return a sizable payload for histograms.  This is because saveAs is done through the normal query mechanism and simply passes the datapoints that were saved back to the caller.  In the case of histograms this would be the entire serialized …
> Added period based chunking, fixed period evaluation bug and added count aggregator to rollup query.

- pom.xml
- test/java/com/arpnetworking/metrics/portal/reports/impl/EmailSenderTest.java
Apparently `simplejavamail` has a sneaky dependency on `net.markenwerk.utils.mail.dkim`. I pulled it in, and added a mock SMTP server library for testing, so that messages actually get sent through `simplejavamail` instead of it being mocked out the whole time. (Maybe this should be an integration test? It seems conceptually very similar to using WireMock, so I made it a unit test.)
> add missing email-sending dependency

- app/com/arpnetworking/metrics/portal/scheduling/JobExecutorActor.java
- app/controllers/ReportController.java
Currently, we have to wait for the anti-entropy mechanism to run before the job gets picked up.
Tested manually. Will soon be able to write an automated integration test (#243).
> when ReportController adds/updates/deletes a job, reload it immediately

- app/com/arpnetworking/metrics/portal/scheduling/CachedJob.java
- app/com/arpnetworking/metrics/portal/scheduling/impl/NeverSchedule.java
- app/com/arpnetworking/metrics/portal/scheduling/impl/OneOffSchedule.java
- app/com/arpnetworking/metrics/portal/scheduling/impl/PeriodicSchedule.java
- main/config/logback-console.xml
- main/config/logback.xml
- pom.xml
Before, logging a `CachedJob`:
```json
{
"time": "2019-07-03T22:29:53.507Z",
"name": "log",
"level": "info",
"data": {
"message": "job has no more scheduled runs",
"cachedJob": {
"_id": "a2b66b0",
"_class": "com.arpnetworking.metrics.portal.scheduling.CachedJob"
}
},
"context": {
"host": "f1434c837e0b",
"processId": "1",
"threadId": "mportal-akka.actor.default-dispatcher-16",
"logger": "c.a.m.p.s.JobExecutorActor",
"line": "236",
"file": "JobExecutorActor.java",
"class": "com.arpnetworking.metrics.portal.scheduling.JobExecutorActor"
},
"id": "48d707ae-a1ec-4f33-be30-7d48e67dc665",
"version": "0"
}
```
(Why does it think there no scheduled runs? What are the parameters of the schedule?)
After:
```json
{
"time": "2019-07-03T22:37:48.931Z",
"name": "log",
"level": "info",
"data": { …
```
> improve logging for time-related stuff

- app/com/arpnetworking/kairos/service/KairosDbServiceImpl.java
- app/controllers/KairosDbProxyController.java
- test/java/com/arpnetworking/kairos/service/KairosDbServiceImplTest.java
- test/resources/com/arpnetworking/kairos/service/KairosDbServiceImplTest.testFiltersRollupOverrideForTagsQueries.backend_response.json
- test/resources/com/arpnetworking/kairos/service/KairosDbServiceImplTest.testFiltersRollupOverrideForTagsQueries.request.json
- test/resources/com/arpnetworking/kairos/service/KairosDbServiceImplTest.testSelectsRollupMetricsBasedOnAggregate.backend_response.json
In grafana, if you tried to use the rollup override suffix you'd get no tags back as it wasn't a valid metric name.  This modifies the proxy to remove the _! suffix if it sees it on a queryMetricTags request.
> Fixed issue with rollup override (_!) not returning tags.

- app/com/arpnetworking/metrics/portal/reports/impl/chrome/DevToolsFactory.java
- app/com/arpnetworking/metrics/portal/reports/impl/chrome/DevToolsServiceWrapper.java
Currently, the tab lingers, which could very easily become a serious memory leak. Oops.
- Before the fix, running `ps` after 0, 1, 20, and 40 Chrome-based reports have completely finished:
```
~ $ docker exec -it metrics-portal-1 ps -ef -o pid,rss,comm,args   # 0
PID   RSS  COMMAND          COMMAND
1 233m java             /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -XX:+Hea
84    4 ps               ps -ef -o pid,rss,comm,args
~ $ docker exec -it metrics-portal-1 ps -ef -o pid,rss,comm,args   # 1
PID   RSS  COMMAND          COMMAND
1 233m java             /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -XX:+Hea
102  33m chrome           /usr/lib/chromium/chrome --no-first-run --remote-de
106  15m chrome           /usr/lib/chromium/chrome --type=zygote --no-sandbox
124  42m chrome …
```
> When Chrome devtools are closed, close the entire tab

- app/com/arpnetworking/rollups/NoMoreRollups.java
- app/com/arpnetworking/rollups/RollupDefinition.java
- app/com/arpnetworking/rollups/RollupExecutor.java
- app/com/arpnetworking/rollups/RollupFetch.java
- app/com/arpnetworking/rollups/RollupManager.java
- app/global/MainModule.java
- test/java/com/arpnetworking/rollups/RollupExecutorTest.java
- test/java/com/arpnetworking/rollups/RollupManagerTest.java
Adds a cluster sharded actor that holds rollups to be performed, with an actor for actually executing those rollups.
Currently the actors are not all fully configured, this will also be followed with a PR to remove the rollup execution code out of the RollupGenerator actor.  That actor will instead send RollupDefinitions to the new RollupManager actor.
> Use an independent actor for holding rollups to be performed.

- app/com/arpnetworking/metrics/portal/reports/impl/chrome/OriginConfig.java
- test/java/com/arpnetworking/metrics/portal/reports/impl/chrome/OriginConfigTest.java
An instance of this class defines policies to be implemented for a particular origin, e.g. what paths should be requestable/navigable-to or what headers should be added to requests to that origin.
Potentially controversial: I've added Jackson annotations to this class so that it's deserializable from JSON. I'm hoping to use Jackson to deserialize the `Map<String, OriginConfig>` in the application.conf file, because manually validating fields' presence/types is a pain. I'd be willing-but-not-thrilled to budge on this.
> add OriginConfig class

- app/com/arpnetworking/metrics/portal/reports/impl/chrome/CachingChromeServiceFactory.java
- app/com/arpnetworking/metrics/portal/reports/impl/chrome/DefaultDevToolsFactory.java
- app/global/MainModule.java
- test/java/com/arpnetworking/metrics/portal/reports/ReportExecutionContextTest.java
- test/java/com/arpnetworking/metrics/portal/reports/impl/chrome/BaseChromeTestSuite.java
- test/java/com/arpnetworking/metrics/portal/reports/impl/chrome/DefaultDevToolsFactoryTest.java
- test/java/com/arpnetworking/metrics/portal/reports/impl/chrome/DevToolsServiceWrapperTest.java
- test/java/com/arpnetworking/metrics/portal/reports/impl/chrome/HtmlScreenshotRendererTest.java
Functionally, this is a no-op:
- refactor DevToolsFactory creation to make it possible for multiple instances to share the same Chrome instances (this solves some test nondeterminism I was running into)
- add some new tests for Chrome-related stuff
> refactor DevToolsFactory creation, and improve Chrome-rendering tests

- pom.xml
This results in the following block getting added to the effective pom (as displayed by `mvn help:effective-pom`), in the `plugins` section:
```xml
<plugin>
<artifactId>maven-gpg-plugin</artifactId>
<version>1.6</version>
<executions>
<execution>
<id>sign-artifacts</id>
<phase>verify</phase>
<goals>
<goal>sign</goal>
</goals>
<configuration>
<gpgArguments combine.children="append">
<arg>--pinentry-mode</arg>
<arg>loopback</arg>
</gpgArguments>
<keyname>arpnet</keyname>
<passphraseServerId>arpnet</passphraseServerId>
</configuration>
</execution>
</executions>
</plugin>
```
That looks like a properly-merged version of the parent and child plugin-configs.
> add args to gpg to hopefully fix the Maven signing issue

- pom.xml
This reverts commit ccb58248f34a30e9d0ba396c27abce6ad1a416eb.
The `sign` goal is executed during the `verify` phase, and since #298 was merged, when I `mvn verify` locally it fails with
```
gpg: skipped "arpnet": No secret key
gpg: signing failed: No secret key
```
> Revert "add args to gpg to hopefully fix the Maven signing issue (#298)"

- pom.xml
#298 accidentally enabled `maven-gpg-plugin` by default, which is why it was running on every `verify`. IIUC, by putting the config in `<pluginManagement>` instead, it should affect how the plugin runs _when it does_, but it shouldn't affect _whether_ the plugin runs.
> same as #298, but apply the change in <pluginManagement> instead of main <plugins>

- app/com/arpnetworking/kairos/client/KairosDbClient.java
- app/com/arpnetworking/kairos/client/KairosDbClientImpl.java
- app/com/arpnetworking/kairos/client/models/TagNamesResponse.java
- app/com/arpnetworking/kairos/service/KairosDbService.java
- app/com/arpnetworking/kairos/service/KairosDbServiceImpl.java
- app/controllers/KairosDbProxyController.java
- conf/portal.application.conf
- test/java/com/arpnetworking/kairos/client/KairosDbClientImplTest.java
- test/java/com/arpnetworking/kairos/client/models/TagNamesResponseTest.java
- test/java/com/arpnetworking/kairos/service/KairosDbServiceImplTest.java
- test/resources/com/arpnetworking/kairos/client/KairosDbClientImplTest.testListTagNames.response.json
- test/resources/com/arpnetworking/kairos/client/models/TagNamesResponseTest.testTranslationLosesNothing.json
- test/resources/com/arpnetworking/kairos/service/KairosDbServiceImplTest.testFilterTagNamesOnListTagNames.backend_response.json
Add support for excluding tags (by name). Implement first part of this filtering for the list tag names endpoint (http://[host]:[port]/api/v1/tagnames).
> Tag Namer Filtering Part 1

- app/com/arpnetworking/metrics/portal/reports/impl/chrome/DevToolsServiceWrapper.java
- conf/portal.application.conf
- pom.xml
- test/java/com/arpnetworking/metrics/portal/reports/impl/chrome/DevToolsServiceWrapperTest.java
This will make reporting work with newer versions of Chrome. (Thank goodness, the Chrome devtools library recently had a version bump that included the new devtools API.)
Verified locally with `mvn verify` and by creating a tab in non-headless mode and manually driving it to sites in order to verify that the rules specified in the application.conf were enforced. Hopefully it passes on Travis too.
> upgrade to using Chrome devtools Fetch API instead of Network

- app/com/arpnetworking/rollups/RollupForwarder.java
- app/com/arpnetworking/rollups/RollupGenerator.java
- app/global/MainModule.java
This addresses a problem with the individual RollupExecutor actors not being able to get work from their local RollupManager due to it being behind a ConsistentHashPool.  Instead of the pool instantiating the RollupManager it now instantiates a RollupForwarder which in turn references the local RollupManager.  This allows the RollupManager to be created as an eager singleton and passed to the RollupExecutors so they can talk to the local instance.
> Added RollupForwarder to use as an indirection level for between the cluster pool and RollupManager

- app/com/arpnetworking/metrics/portal/reports/impl/chrome/DefaultDevToolsFactory.java
- app/com/arpnetworking/metrics/portal/reports/impl/chrome/DevToolsNetworkConfigurationProtocol.java
- app/com/arpnetworking/metrics/portal/reports/impl/chrome/DevToolsServiceWrapper.java
- conf/portal.application.conf
- test/java/com/arpnetworking/metrics/portal/reports/impl/chrome/DefaultDevToolsFactoryTest.java
- test/java/com/arpnetworking/metrics/portal/reports/impl/chrome/DevToolsNetworkConfigurationProtocolTest.java
- test/java/com/arpnetworking/metrics/portal/reports/impl/chrome/DevToolsServiceWrapperTest.java
- add enum for whether to use old or new DevTools protocol
- refactor request-interception code into that enum (copying old code from 8c0fe5cd25ac3f28d1b337af5ce2155893f70b95)
- add configuration option from app-config to control which strategy to use
> add configuration option to use deprecated DevTools request-interception protocol

- app/assets/javascripts/classes/reports/EditReportViewModel.ts
- app/assets/javascripts/classes/reports/Models.ts
- app/com/arpnetworking/metrics/portal/reports/impl/DatabaseReportRepository.java
- app/models/ebean/GrafanaReportPanelReportSource.java
- app/models/ebean/WebPageReportSource.java
- app/models/internal/impl/WebPageReportSource.java
- app/models/view/impl/WebPageReportSource.java
- conf/db/migration/metrics_portal_ddl/V19__drop_web_page_triggering_event.sql
- public/html/reports/EditSourceViewModel.html
- test/java/com/arpnetworking/metrics/portal/TestBeanFactory.java
- test/java/com/arpnetworking/metrics/portal/integration/repositories/DatabaseReportRepositoryIT.java
- test/java/com/arpnetworking/metrics/portal/reports/ReportExecutionContextTest.java
- test/java/models/view/ReportSerializationTest.java
- test/resources/models/view/ReportSerializationTest.testValidReport.json
It's never even used in the code currently; and the current behavior of "simple web pages get screenshotted on `load`, Grafana pages get screenshotted on `reportrendered`" seems perfectly adequate for all foreseeable use cases.
> remove concept of "triggering event" from web-based reports

- app/com/arpnetworking/metrics/portal/reports/impl/DatabaseReportRepository.java
- app/com/arpnetworking/metrics/portal/reports/impl/NoReportRepository.java
- app/com/arpnetworking/metrics/portal/scheduling/CachedJob.java
- app/com/arpnetworking/metrics/portal/scheduling/JobRepository.java
- test/java/com/arpnetworking/metrics/portal/integration/repositories/DatabaseReportRepositoryIT.java
- test/java/com/arpnetworking/metrics/portal/scheduling/impl/MapJobRepository.java
Currently, `DatabaseReportRepository.getJobLastRun()` will throw if a job has multiple completed executions. This fixes that.
Along the way, I decided that the semantics for that method were wrong, and it should return
`job.executions().filter(hasCompleted).map(scheduledFor).max()`
rather than
`job.executions().filter(hasCompleted).map(completedAt).max()`
, in order to catch up in weird edge cases where one run doesn't complete until after it is next scheduled to start.
> fix exception when a report has multiple executions; and subtly change semantics for scheduling

- conf/portal.application.conf
It currently isn't declared in the configfile, so no node has that role, so anti-entropy isn't getting run.
> add report anti-entropy role to cluster

- app/com/arpnetworking/kairos/client/models/DataPoint.java
- app/com/arpnetworking/kairos/client/models/MetricsQueryResponse.java
- pom.xml
- test/java/com/arpnetworking/metrics/portal/integration/controllers/KairosDbProxyControllerIT.java
Make data point optional to support gaps aggregator. Remove internal model conversion instead of propagating change down deprecated path.
> Nullability Fix for Gaps Aggregator

- README.md
- app/assets/javascripts/classes/reports/EditReportViewModel.ts
- app/assets/javascripts/classes/reports/Models.ts
- app/com/arpnetworking/metrics/portal/reports/ReportFormat.java
- app/com/arpnetworking/metrics/portal/reports/ReportInterval.java
- app/models/internal/Features.java
- app/models/internal/impl/DefaultFeatures.java
- conf/portal.application.conf
- public/html/reports/ReportsViewModel.html
Extends the configuration, client-side injected features, as well as report ui code to support configuration of:
* Sources
* Formats
* Recipients
* Intervals
All are enabled by default, although reporting itself is off by default.
> Allow control of various aspects of report configuration.

- app/com/arpnetworking/rollups/RollupExecutor.java
The KairosDB SaveAsAggregator bakes in the assumption that you're not saving a previous save-as, otherwise the `saved_from` tag thats added to the output series by default will conflict with the existing tag.
Now that we're rolling up roll-ups, this conflict occurs in RollupExecutor. I figured the actual fix would be to update SaveAs (see https://github.com/ddimensia/kairosdb/pull/3) but since Metrics Portal will likely be run against other instances of KairosDB they'll still have this conflict outside of that fork and I think the appropriate action is just to turn this off entirely.
> explicitly disable add_saved_from in RollupExecutor

- app/com/arpnetworking/kairos/service/KairosDbServiceImpl.java
- test/java/com/arpnetworking/kairos/service/KairosDbServiceImplTest.java
- test/java/com/arpnetworking/metrics/portal/TestBeanFactory.java
The logic for determining whether a query can be optimized to use rollups / which rollup to use is broken, and it will sometimes use a rollup even when it shouldn't.
This is a problem in Dropbox's production environment: [Grafana](http://drl/q34th87h4378og)
- There are two queries, identical except that one uses the `_!` feature to prevent use of rollups.
- Clearly, they should return the same value, because rollup-usage should be a pure optimization, invisible to the user. But they don't.
- The query has two aggregators: `count(1m)` and `count(1h)`. The first aggregator, though, is not sampling-aligned, which leads to [it being ignored](https://github.com/ArpNetworking/metrics-portal/blob/e8b8df96e566963f2dbd94c59a539fe5a5731091/app/com/arpnetworking/kairos/service/KairosDbServiceImpl.jav …
> Fix query-rewriting for rollups

- app/com/arpnetworking/kairos/service/KairosDbServiceImpl.java
- test/java/com/arpnetworking/kairos/service/KairosDbServiceImplTest.java
Should be a behavioral no-op. Depends on #352 -- [this commit range](https://github.com/ArpNetworking/metrics-portal/pull/353/files/fd76e39437cb6563ea61acaf4901371022303a7d..5305ff56e9433e129e49fd5888716342b5de72f1) includes only changes since then.
> refactor out a chunk of rollup query-rewriting

- app/com/arpnetworking/rollups/RollupDefinition.java
- app/com/arpnetworking/rollups/RollupGenerator.java
- test/java/com/arpnetworking/rollups/RollupExecutorTest.java
- test/java/com/arpnetworking/rollups/RollupManagerTest.java
I think we want each rollup-job to be as atomic as feasible, and that means having each job consist of writing a _single_ timestamp, not multiple.
(We were already doing this in practice. I'm just simplifying the data model to enforce this constraint.)
> compute rollup-job end time from start time and period, to increase atomicity

- app/controllers/KairosDbProxyController.java
- conf/portal.application.conf
- test/java/controllers/KairosDbProxyControllerTest.java
- test/java/controllers/package-info.java
This prevents queries from being proxied through to kairos if no aggregators exist on the requested metrics.  This prevents large histogram responses on high-cardinality metrics when someone first sets up a grafana query.  Ideally this should be blocked in the grafana plugin also.
> Added 400 response when a metrics query doesn't contain aggregators for all queried metrics.

- app/com/arpnetworking/metrics/portal/scheduling/JobExecutionRepository.java
- app/models/internal/scheduling/JobExecution.java
- test/java/com/arpnetworking/metrics/portal/scheduling/impl/MapJobExecutionRepository.java
Introduce a new type of repository, `JobExecutionRepository`, that pulls out all execution related methods from the `JobRepository` interface.
In the case of Alerts, these two repos will not be backed by the same implementation, and in general that is not a strict requirement and so it makes sense to consider them separately (although in the case of reports, both will still just use the same SQL Ebean impls underneath).
Relatedly, some alert APIs will need to retrieve the state of the most recent execution and so we need an internal model to represent these. We did not have this defined previously because reports are write-only at the moment.
Perhaps somewhat contentiously, I've added another ADT-like hiearchy in `JobExecution` rather than stuff all fields as top-level `Optional`s. This …
> interfaces for internal JobExecution

- app/com/arpnetworking/kairos/client/KairosDbClientImpl.java
- app/global/MainModule.java
- test/java/com/arpnetworking/kairos/client/KairosDbClientImplTest.java
- test/java/com/arpnetworking/metrics/portal/integration/controllers/KairosDbProxyControllerIT.java
Log line before (gotten by tailing the logs after `mvn docker:start` with a tweaked Logback config to enable debug-level logging, then hitting the container with a KairosDB query request):
```
{
...
"query": {
"_id": "356c4af6",
"_class": "com.arpnetworking.kairos.client.models.MetricsQuery",
"cache_time": 0
}
...
}
```
Log line after:
```
{
...
"query": {
"metrics": [
{
"aggregators": [
{
"sampling": {
"unit": "minutes",
"value": 1
},
"name": "percentile",
"align_sampling": true,
"align_start_time": true,
"percentile": "0.999"
}
],
"limit": 0,
"tags": {
"build_channel": [
"beta",
"stable"
]
},
"name": "some_metric/foo/bar",
"group_by": [
{
"name": "tag",
"tags": [
"platform",
"build_channel"
]
}
]
}
],
"start_absolute": 1586772000000,
"end_absolute": 1586772000000,
"cache_time": 0
}
... …
```
> fix KairosDB query-logging to actually include the query

- app/com/arpnetworking/rollups/LastDataPointsMessage.java
- app/com/arpnetworking/rollups/RollupDefinition.java
- app/com/arpnetworking/rollups/RollupExecutor.java
- app/com/arpnetworking/rollups/RollupGenerator.java
- app/com/arpnetworking/rollups/TagNamesMessage.java
- test/java/com/arpnetworking/rollups/RollupExecutorTest.java
- test/java/com/arpnetworking/rollups/RollupGeneratorTest.java
- test/java/com/arpnetworking/rollups/RollupManagerTest.java
This consists of:
- Adding the `_filterTags` field to tell the RollupExecutors which tags to slice on. This field isn't used yet, it's just left at its default empty value, but that will change.
- Generalizing `_groupByTags` (used to populate the rollup-query's `group_by`) to include tag _values_ as well as names. (new name `_allMetricTags`)
Together, these will facilitate partition-and-retry logic: when a job fails, we can pick a tag from `_allMetricTags` that we haven't yet filtered by, and add various values to `_filterTags` for various sub-jobs.
> Rollups: add filter-by-tag field(s) to RollupDefinition

- app/com/arpnetworking/metrics/portal/reports/ReportExecutionRepository.java
- app/com/arpnetworking/metrics/portal/reports/impl/DatabaseReportExecutionRepository.java
- app/com/arpnetworking/metrics/portal/reports/impl/DatabaseReportRepository.java
- app/com/arpnetworking/metrics/portal/reports/impl/NoReportExecutionRepository.java
- app/com/arpnetworking/metrics/portal/reports/impl/NoReportRepository.java
- app/com/arpnetworking/metrics/portal/scheduling/CachedJob.java
- app/com/arpnetworking/metrics/portal/scheduling/JobCoordinator.java
- app/com/arpnetworking/metrics/portal/scheduling/JobExecutorActor.java
- app/com/arpnetworking/metrics/portal/scheduling/JobRef.java
- app/com/arpnetworking/metrics/portal/scheduling/JobRepository.java
- app/controllers/ReportController.java
- app/global/MainModule.java
- app/models/ebean/Report.java
- app/models/ebean/ReportExecution.java
- conf/portal.application.conf
- test/java/com/arpnetworking/metrics/portal/TestBeanFactory.java
- test/java/com/arpnetworking/metrics/portal/integration/repositories/DatabaseReportExecutionRepositoryIT.java
- test/java/com/arpnetworking/metrics/portal/integration/repositories/DatabaseReportRepositoryIT.java
- test/java/com/arpnetworking/metrics/portal/scheduling/JobCoordinatorTest.java
- test/java/com/arpnetworking/metrics/portal/scheduling/JobExecutorActorTest.java
- test/java/com/arpnetworking/metrics/portal/scheduling/JobMessageExtractorTest.java
- test/java/com/arpnetworking/metrics/portal/scheduling/impl/MapJobRepository.java
This pulls out all relevant execution logic from `DatabaseReportRepository` into `DatabaseReportExecutionRepository`.
Depends on #360.
> Implement JobExecutionRepository for Reports

- app/com/arpnetworking/metrics/portal/reports/impl/DatabaseReportExecutionRepository.java
- app/com/arpnetworking/metrics/portal/scheduling/JobCoordinator.java
- app/models/internal/scheduling/JobExecution.java
* Remove static methods for createAntiEntropyRunnable and just use a method reference instead.
* Generate `hashCode`, `equals`, and `toString` for all JobExecution variants.
> Cleanup anti-entropy, generate standard methods for JobExecution

- app/com/arpnetworking/metrics/portal/reports/impl/DatabaseReportExecutionRepository.java
- conf/postgresql.application.conf
It's currently not bound to anything by default so the injector throws from within CachedJob as it tries to fetch the repository impl.
> Enable DatabaseReportExecutionRepository for postgres config

- app/com/arpnetworking/rollups/RollupPartitioner.java
- test/java/com/arpnetworking/rollups/RollupPartitionerTest.java
(In practice, it looks like the failures passed in here are CompletionExceptions.)
> rollups: retry: dig into exception cause to find KDB exception

- test/java/com/arpnetworking/metrics/portal/integration/repositories/DatabaseReportExecutionRepositoryIT.java
All of this was duplicated into [JobExecutionRepositoryIT](https://github.com/ArpNetworking/metrics-portal/blob/4de7284cf260ef3d634fa3e4fe99138a52ba4ed5/test/java/com/arpnetworking/metrics/portal/integration/repositories/JobExecutionRepositoryIT.java) in #380, so we don't need to have it in two places.
> refactor report execution test

- app/com/arpnetworking/metrics/portal/scheduling/impl/PeriodicSchedule.java
- test/java/com/arpnetworking/metrics/portal/scheduling/impl/PeriodicScheduleTest.java
Add support for `PeriodicSchedule` instances whose interval is several periods (e.g. 15 minutes instead of just a minute). This only alters the internal model, so for backwards compatibility, the periodCount is set to 1 by default.
I also took this opportunity to refactor the `unboundedNextRun` code. I removed the check to see if the run was before `getRunAtAndAfter` because this is already handled in `BaseSchedule`, and indeed the doc there specifies that subclasses do not need to make this check. This change only a single offset-related test, and I consider that change a bug fix. We were skipping a run that was otherwise valid as it fell between the specified `runAtAndAfter` and `runUntil` values.
> Add support for periodCount > 1 in PeriodicSchedule

- app/com/arpnetworking/kairos/client/models/SamplingUnit.java
- app/com/arpnetworking/metrics/portal/query/QueryExecutor.java
- app/com/arpnetworking/metrics/portal/query/QueryExecutorRegistry.java
- app/com/arpnetworking/metrics/portal/query/impl/DelegatingQueryExecutor.java
- app/com/arpnetworking/metrics/portal/query/impl/NoQueryExecutor.java
- app/global/MainModule.java
- app/models/internal/BoundedMetricsQuery.java
- app/models/internal/impl/DefaultBoundedMetricsQuery.java
- conf/portal.application.conf
I've isolated these changes from the Alert execution code I've written, since there were a few things necessary to get that into a working state.
Changes Introduced
* We need a notion of time range on the query model used for the executor. This was previously in the class `MetricsQuery`, but instead I've introduced a separate `BoundedMetricsQuery` that keeps all the same fields along with a time range. This distinction is necessary because alert query definitions do not need a time range specified since it's inferred at execution time based on the scheduler and period hint (see next bullet).
* executors can now specify a "periodHint" via `QueryExecutor#periodHint`. This is *necessary* for alert evaluation to ensure we don't miss any gaps in a query. For example, an alert query can be …
> QueryExecutor RFC: Time-bounded queries and delegated executor

- app/global/MainModule.java
Guice wiring. The repositories are still empty and even if they weren't the execution isn't configured. But this is still beneficial so that the execution wiring is in place before the actual logic.
> AlertJobCoordinator guice bindings

- app/models/internal/TimeSeriesResult.java
- app/models/view/TimeSeriesResult.java
I'd like to include a bunch of testcases in a different diff as JSON files and this makes that possible. There were some annotations before but Jackson cannot resolve the interfaces without encoded type information. Since most of these types have a backing `DefaultXXX` class, I included those as the default deserialize types.
> Add Jackson annotations to the Query interfaces

- app/global/MainModule.java
[v0.9.31 bumped our version of `apache-http-sink-extra` from 0.8.2 to 0.11.1.](https://github.com/ArpNetworking/metrics-portal/compare/metrics-portal-0.9.30...metrics-portal-0.9.31#diff-600376dffeb79835ede4a0b285078036R107) (ctrl-f `metrics.client.http.version`)
[This changed the default Protobuf version from V1 to V3.](https://github.com/ArpNetworking/metrics-apache-http-sink-extra/compare/apache-http-sink-extra-0.8.2...apache-http-sink-extra-0.11.1#diff-02eafa443f9a5351d82c7a69783fc847R241) (ctrl-f `Sink.java`, unfold, ctrl-f `ClientV3`)
So, that version bump _should_ have been accompanied by this endpoint modification, but it wasn't.
I've verified using the `metrics/build/start.sh` script that there are loads of ProtobufV1 parse-failures in MAD's logs on master; and that this change …
> use protobuf V3 endpoint instead of V1

- app/com/arpnetworking/rollups/RollupExecutor.java
- conf/portal.application.conf
- test/java/com/arpnetworking/rollups/RollupExecutorTest.java
I opted for leaving this non-optional since the documented behavior is to use whatever is configured in kairos if you set it to 0.
I suppose this means the only use case that would not be covered would be if you have a default TTL but never want your rollups to have a TTL (but this seems weird so I left as is)
> Add a TTL to rollup series

- app/global/MainModule.java
Stack trace in prod:
```
Caused by: akka.actor.InvalidActorNameException: actor name [rollup-metrics-discovery] is not unique!
at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:129)
at akka.actor.dungeon.Children$class.reserveChild(Children.scala:135)
at akka.actor.ActorCell.reserveChild(ActorCell.scala:429)
at akka.actor.dungeon.Children$class.makeChild(Children.scala:275)
at akka.actor.dungeon.Children$class.attachChild(Children.scala:49)
at akka.actor.ActorCell.attachChild(ActorCell.scala:429)
at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:753)
at global.MainModule$RollupManagerProvider.get(MainModule.java:925)
at global.MainModule$RollupManagerProvider.get(MainModule.java:1)
```
> fix actor name conflict

- conf/portal.application.conf
Role was missing from configuration so the actor is never instantiated.
> add alert anti-entropy role to cluster

- app/com/arpnetworking/metrics/portal/scheduling/impl/BaseSchedule.java
- app/global/MainModule.java
- test/java/com/arpnetworking/metrics/portal/scheduling/impl/BaseScheduleTest.java
This is causing a failure in alert execution, since the schedule was set to run after `Instant.MIN` but the PeriodicSchedule internally requires that this instant correspond to a valid Date.
I think it would make more sense to place this constraint on PeriodicSchedule rather than BaseSchedule (since the latter does not expose any zoned functionality) but it isn't clear how I can do that since the `runAtAndAfter` field is defined in the BaseSchedule.
> Schedules should disallow Instant.MIN for runAtAndAfter

- app/com/arpnetworking/metrics/portal/scheduling/JobCoordinator.java
- conf/portal.application.conf
- test/java/com/arpnetworking/metrics/portal/scheduling/JobCoordinatorTest.java
It seems that the JobCoordinator will not perform anti-entropy until after the first timer fires 1 hour after startup. This ordinarily isn't a problem because as I understand it the actor system will buffer tick messages to the coordinator between restarts, since it's a cluster singleton. However in the cases where an entirely new coordinator is started or all instances are shut down, the initial wait is unnecessary.
> Run anti-entropy at JobCoordinator startup

- app/com/arpnetworking/rollups/FailableMessage.java
- app/com/arpnetworking/rollups/LastDataPointsMessage.java
Relevant excerpt from the stack trace
```json
{
"message":"Failed to serialize remote message [class com.arpnetworking.rollups.RollupExecutor$FinishRollupMessage] using serializer [class akka.serialization.JavaSerializer]. Transient association error (association remains live)",
"cause": {
"type":"java.io.NotSerializableException",
"message":"java.util.Optional"
}
}
```
> Stop using Optional in FailableMessage since it's serialized

- app/com/arpnetworking/metrics/portal/reports/ReportExecutionContext.java
- app/com/arpnetworking/metrics/portal/reports/impl/DatabaseReportRepository.java
- app/com/arpnetworking/metrics/portal/scheduling/Schedule.java
- app/com/arpnetworking/metrics/portal/scheduling/impl/BoundedSchedule.java
- app/com/arpnetworking/metrics/portal/scheduling/impl/NeverSchedule.java
- app/com/arpnetworking/metrics/portal/scheduling/impl/OneOffSchedule.java
- app/com/arpnetworking/metrics/portal/scheduling/impl/PeriodicSchedule.java
- app/com/arpnetworking/metrics/portal/scheduling/impl/UnboundedPeriodicSchedule.java
- app/global/MainModule.java
- test/java/com/arpnetworking/metrics/portal/scheduling/impl/BaseScheduleTest.java
- test/java/com/arpnetworking/metrics/portal/scheduling/impl/UnboundedPeriodicScheduleTest.java
Introduce an unbounded periodic schedule, motivated by the alerting use case since alerts do not need backfilling behavior.
By analogy I've also renamed the `BaseSchedule` class to `BoundedSchedule` to make it clear that it makes certain assumptions about the subtype behavior. I've also refactored `NeverSchedule` to no longer be bounded since that didn't make much sense.
EDITED: This was originally just to collect feedback but I decided to mark this as a proper PR.
> Unbounded periodic schedule

- app/controllers/AlertController.java
- test/java/controllers/AlertControllerTest.java
Alert controller 2/2. This builds simple pagination on top of the view model and single alert endpoint introduced in #439.
We'll likely want some form of caching as the alerts grow, since this makes a db call to join each definition with its most recent execution result.
> alert pagination

- app/controllers/KairosDbProxyController.java
- app/global/MainModule.java
- test/java/com/arpnetworking/kairos/service/KairosDbServiceImplTest.java
- test/java/controllers/KairosDbProxyControllerTest.java
Straightforward refactor that moves out the KairosDB service into its own provider since it should be shared between the KairosDBQueryExecutor and the ProxyController.
I noticed this because the query executor failed with a lack of bindings during an end-to-end alert evaluation test.
> Extract out KairosDBService configuration into a provider

- app/com/arpnetworking/metrics/portal/scheduling/impl/UnboundedPeriodicSchedule.java
- app/global/MainModule.java
- test/java/com/arpnetworking/metrics/portal/scheduling/impl/UnboundedPeriodicScheduleTest.java
Bug-fix for a scheduling issue caught during an end-to-end alert evaluation test.
For times that land *exactly* on a period, we would return that same period as the next evaluation time. This was because the order of the `orElse` and `Duration::plus` operations were inversed, since we always want to perform that `plus` regardless of if there was a previous run or not. The time returned by the schedule should *always* be in the future. I've included a test that caught this bug and updated the other tests since their behavior was actually incorrect.
> Fix a bug with unbounded schedule fixed points

- app/com/arpnetworking/metrics/portal/alerts/impl/DailyPartitionCreator.java
- app/models/internal/impl/DefaultAlertEvaluationResult.java
- app/models/internal/impl/DefaultReportResult.java
- test/java/com/arpnetworking/metrics/portal/alerts/impl/DailyPartitionCreatorTest.java
- test/java/com/arpnetworking/metrics/portal/integration/repositories/JobExecutionRepositoryIT.java
Ebean's SQLQuery doesn't appear to be working, and SQLUpdate does not
support SELECT statements (which is necessary to call the function).
The existing test suite didn't catch this issue because it created the
partitions for the current date during migrations, and so the partition
creation would silently fail while the tests would still pass. I've
added a new test which creates a scheduled event in the past, which
catches this oversight.
I've verified this locally by running the container separately and then executing the test suite. The expected partitions exist in the database.
> Use JDBC conn directly within DailyPartitionCreator

- app/com/arpnetworking/metrics/portal/alerts/impl/DailyPartitionCreator.java
- app/com/arpnetworking/metrics/portal/scheduling/JobExecutorActor.java
The executor doesn't play well with the UnboundedExecutionSchedule since it recomputes the nextRun time on every tick. I've changed it to cache the computed next run and only recompute it when the execution has been attempted (either succeeds or fails). This should not have different behavior with the scheduling granularity we currently deal with.
> stop polling the schedule every tick within JobExecutorActor

- app/com/arpnetworking/metrics/portal/alerts/impl/DatabaseAlertExecutionRepository.java
- test/java/com/arpnetworking/metrics/portal/integration/repositories/DatabaseAlertExecutionRepositoryIT.java
- test/java/com/arpnetworking/metrics/portal/integration/repositories/DatabaseReportExecutionRepositoryIT.java
- test/java/com/arpnetworking/metrics/portal/integration/repositories/JobExecutionRepositoryIT.java
A silly bug, but it's happened nonetheless.
We want to update an alert execution, so we first check it exists by querying for the most recent execution _for this particular ID_.
We want to update an alert execution, so we first check it exists by querying for the most recent execution. 
Notice that the above never involves Alert ID.
---
Fortunately, this blows up because we only expect to ever retrieve a single result, instead of several.
The fix is straightforward: add the missing where clause. I've also included a sanity check test that I used to reproduce and identify the issue.
> bugfix: add alert id to where clause when inserting an execution

- app/com/arpnetworking/metrics/portal/alerts/impl/PluggableAlertRepository.java
- test/java/com/arpnetworking/metrics/portal/alerts/AlertExecutionContextTest.java
- test/java/com/arpnetworking/metrics/portal/alerts/impl/PluggableAlertRepositoryTest.java
- test/java/controllers/AlertControllerTest.java
These are not required fields, and on the serialization end they are
dropped when they are considered "zero values" e.g. 0 for long. Let's
just explicitly default to these.
Additionally we log the config error instead of completely failing to start up.
> default to empty values for version/enabled

- app/com/arpnetworking/metrics/portal/alerts/impl/PluggableAlertRepository.java
- app/com/arpnetworking/metrics/portal/config/impl/NullConfigProvider.java
- test/java/com/arpnetworking/metrics/portal/alerts/impl/PluggableAlertRepositoryTest.java
- test/java/controllers/AlertControllerTest.java
Now we won't consider a repository open until it receives at least one update from the inner `ConfigProvider`. If that provides an empty stream, we can be confident that the repository is truly empty rather than unloaded.
> wait for reload when opening the alert repository

- app/com/arpnetworking/metrics/portal/alerts/impl/PluggableAlertRepository.java
- app/com/arpnetworking/metrics/portal/scheduling/JobCoordinator.java
- test/java/com/arpnetworking/metrics/portal/alerts/impl/PluggableAlertRepositoryTest.java
- test/java/controllers/AlertControllerTest.java
This is intended to solve the following problem:
1. Metrics portal is operating in a clustered state, with N > 1 nodes.
2. The entire fleet is restarted, perhaps during a deployment
3. The JobCoordinator for alerts restarts and then attempts to run anti-entropy to reconcile jobs
4. The anti-entropy job runs on a node that has not yet loaded its alert definitions, and so it sees an empty repository
5. Anti-entropy "succeeds" and there are no alerts until the next tick occurs in one hour.
> run anti-entropy when the pluggable alert repository reloads

- app/global/MainModule.java
Several actor refs handed out in `MainModule` are incorrectly returning the cluster singleton manager, when instead they should be returning a reference to the proxy. 
The proxy **must be used** instead of the manager, otherwise the message won't be routed to the singleton actor. The rollup singletons are correctly implemented and these changes are based on those providers, e.g. ([RollupMetricsDiscoveryProvider](https://github.com/ArpNetworking/metrics-portal/compare/cluster_singleton_proxy?expand=1#diff-cca88e717fceea609a9f29e31e270390R889))
See https://doc.akka.io/docs/akka/2.5/cluster-singleton.html#an-example for details.
> singletons: return a ref to the proxy, not the manager

- app/com/arpnetworking/metrics/portal/scheduling/JobExecutorActor.java
- test/java/com/arpnetworking/metrics/portal/scheduling/JobExecutorActorTest.java
For whatever reason Akka is not URL encoding the name when run as a
single actor (e.g. in the tests), but it is encoding it in a clustered environment. It
likely does this lazily when the actor name needs to be serialized.
To avoid issues let's just always URL decode before we attempt to use
the name.
> decode the actor name before attempting to deserialize

- app/com/arpnetworking/metrics/portal/scheduling/JobExecutorActor.java
- test/java/com/arpnetworking/metrics/portal/scheduling/JobExecutorActorTest.java
Right now the actor just PoisonPills itself which causes it to get
resurrected by the ClusterSharding manager. Instead we should tell the
manager to kill the child permanently via Passivate.
This unintended resurrection has likely been around for a while, but only became
visible recently since post-resurrection actors previously did nothing meaningful (this changed in #456).
> JobExecutor: request stop from parent via passivate 

- app/com/arpnetworking/metrics/portal/alerts/scheduling/AlertExecutionContext.java
- app/com/arpnetworking/metrics/portal/query/QueryExecutor.java
- app/com/arpnetworking/metrics/portal/query/impl/DelegatingQueryExecutor.java
- app/com/arpnetworking/metrics/portal/query/impl/KairosDbQueryExecutor.java
- app/com/arpnetworking/metrics/portal/query/impl/NoQueryExecutor.java
- test/java/com/arpnetworking/metrics/portal/alerts/AlertExecutionContextTest.java
- test/java/com/arpnetworking/metrics/portal/query/impl/KairosDbQueryExecutorTest.java
We use period hint for the lookback window on a query, but they should be considered separate concepts. One is the minimum range necessary for data, and the other is the minimum frequency that we should poll this query (these turn out to be the max and min of the aggregator sampling, respectively). We don't actually use the former right now, as all queries are evaluated every minute.
The second change is due to the incorrect assumption made that aggregators will always be a unit value (e.g. exactly 1 hour). There's no reason they shouldn't be, and by using `Duration` instead of `ChronoUnit` the lookback should be correctly computed for arbitrary aggregations like 12 hours.
`periodHint` is renamed to `evaluationPeriodHint` for clarity.
> separate lookback and period hint, support non-unit periods

- app/com/arpnetworking/metrics/portal/alerts/impl/DatabaseAlertExecutionRepository.java
- app/com/arpnetworking/metrics/portal/scheduling/JobExecutionRepository.java
- app/controllers/AlertController.java
- test/java/com/arpnetworking/metrics/portal/integration/repositories/JobExecutionRepositoryIT.java
- test/java/controllers/AlertControllerTest.java
When we paginate over alerts, we currently fetch their execution status individually. As you can imagine, this is not very performant as we make a round trip to the DB for every alert.
This adds a batch lookup method which fetches the executions in one go. The query itself is much cheaper per-alert (measured up to 1000 records), so including the decrease in network cost I don't expect latency to be a problem again here for a while.
> Batch fetch alerts from postgres

- app/com/arpnetworking/kairos/service/DefaultQueryContext.java
- app/com/arpnetworking/kairos/service/KairosDbService.java
- app/com/arpnetworking/kairos/service/KairosDbServiceImpl.java
- app/com/arpnetworking/kairos/service/QueryContext.java
- app/com/arpnetworking/kairos/service/QueryOrigin.java
- app/com/arpnetworking/metrics/portal/query/impl/KairosDbQueryExecutor.java
- app/controllers/KairosDbProxyController.java
- app/global/MainModule.java
- conf/portal.application.conf
- test/java/com/arpnetworking/kairos/service/KairosDbServiceImplTest.java
- test/java/com/arpnetworking/metrics/portal/query/impl/KairosDbQueryExecutorTest.java
- test/java/controllers/KairosDbProxyControllerTest.java
We want to avoid the use of rollups in alert evaluation, which could potentially affect correctness. For example, if rollups were continually an hour behind, an hourly sample-aligned query would never see any data.
This adds per-origin (alerts, rest API) controls for enabling rollups. By default rollups are disabled for alerts. If we build sufficient confidence we can re-enable these for alerts in the future.
> Do not use rollups when evaluating alerts

- app/com/arpnetworking/metrics/portal/alerts/impl/DatabaseAlertExecutionRepository.java
- test/java/com/arpnetworking/metrics/portal/integration/repositories/JobExecutionRepositoryIT.java
The state filter should occur on the inner query, before the join. This affected alerts that have at least one successful run when the most recent is a failure.
> Fix bug in batch fetch for last successful evaluation

- app/com/arpnetworking/metrics/portal/scheduling/JobExecutorActor.java
This fixes a regression introduced in #472. killSelf will permanently kill the actor, and it will not be resurrected by the supervisor. We should not do this on DB failure, so instead we rethrow to trigger this behavior.
I've also renamed the method to make it clear it will stop the actor forever.
> rethrow, don't killSelf()

- app/com/arpnetworking/metrics/portal/scheduling/JobExecutorActor.java
Now that _cachedJob is an Optional, we're missing a call to Optional#get().
> Fix a metric being logged in JobExecutorActor

- .github/workflows/build.yml
- .vim/coc-settings.json
- app/com/arpnetworking/metrics/portal/scheduling/JobExecutorActor.java
- maven/maven-wrapper.properties
- pom.xml
- settings.xml
- test/java/com/arpnetworking/metrics/portal/scheduling/JobExecutorActorTest.java
Fixes a bug with reloads that occurs as follows:
* Job begins executing and sets the currentlyExecutingFlag
* Anti-entropy kicks in and sends a `Reload` message.
* Reload thinks that it's been triggered by the completion of a job, and so clears the currentlyExecuting flag
* Reload completes and immediately kicks off a second execution (via tick).
This makes it so we only clear the execution flag if we're sure the Reload message occurred internally, otherwise it's ignored since we'll already reload when the execution completes.
> don't allow for reloads to start another job execution

- pom.xml
it was already declared so there's a duplicate conflict
> fix duplicate plugin issue when releasing

- app/assets/javascripts/classes/GraphVM.ts
- app/assets/javascripts/classes/Series.ts
This is an incremental improvement.
This addresses the case where MAD sends multiple values for the same metric name because it has tags outside of host, service, and cluster. Even "host" is broken today because the clientside code assume host == connection. This is not always the case.
This obviously does not work for histograms or percentiles. However, these are broken at the protocol level. There is a patch in MAD-2.0 to address histograms, although it still won't provide correct client side aggregation until we send the actual histogram over.
> Add client side aggregation of telemetry metrics for the same series.

- app/controllers/KairosDbProxyController.java
- test/java/controllers/KairosDbProxyControllerTest.java
This is from a customer reported issue. And we found a bug with the injected merge aggregator:
> Specifically, we add a merge aggregator to ensure histograms are joined before evaluating additional aggregators (in Metrics Portal; KairosDbProxyController.java:203). Unfortunately, the moving window sampling is a faux sampling interval in that it does not actually generate a data point for 7 days, it just consumes 7 days worth of data, but generates a data point for a single day. the fix is to either:
> 
> Ignore the moving window aggregator when determining the sampling interval to use for the injected merge.
> If the first aggregator is moving window then take the moving window aggregator's sampling interval unit and force the value to 1.
> Force sampling value to 1 for movingWindow aggregator

- app/com/arpnetworking/metrics/portal/alerts/impl/AlertExecutionCacheActor.java
- test/java/com/arpnetworking/metrics/portal/alerts/impl/CachingAlertExecutionRepositoryTest.java
The persistence portion is pretty straightforward:
* Persist all `Put` and `MultiPut` messages.
* Periodically (every 5 minutes) take a snapshot of the entire cache state.
That's it.
The hairy part here was serialization - attempting to serialize the cache directly as a map requires registering a custom mapKey serializer with Jackson (since `CacheKey` isn't a "simple" type). Instead I've created a `CacheSnapshot` type that is essentially a list of `SnapshotEntry`s. The sole purpose of this type is for snapshot ser(de).
Tested locally by running postgres and bringing the server up and down.
> make the alert execution cache persistent
