ArpNetworking/metrics-portal

app/models/ebean/Alert.java
app/models/ebean/Expression.java
app/models/ebean/NagiosExtension.java
conf/db/migration/metrics_portal_ddl/common/V3__create_alerts_and_expressions_table.sql

Ebeans and sql migrations for expressions and alerts

expr-and-alerts-ebeans

---

app/assets/javascripts/classes/ConnectionModel.ts
app/assets/javascripts/classes/protocol/BaseProtocol.ts
app/assets/javascripts/classes/protocol/V1Protocol.ts
app/assets/javascripts/classes/protocol/V2Protocol.ts

Refuse to proxy connections to localhost and add a heartbeat check before considering the connection established.

Streaming Connection Proxying Fixes

---

app/models/ebean/Alert.java
app/models/ebean/Expression.java
app/models/ebean/Host.java
app/models/ebean/NagiosExtension.java
app/models/ebean/PackageVersion.java
app/models/ebean/VersionSet.java
app/models/ebean/VersionSpecification.java
app/models/ebean/VersionSpecificationAttribute.java

... to exclude the `_` prefix. Addresses issue #20

Homgenize ebean-data-class field names

---

README.md
app/com/arpnetworking/metrics/portal/version_specifications/VersionSpecificationRepository.java
app/controllers/VersionSpecificationController.java
app/models/internal/PackageVersion.java
app/models/internal/VersionSet.java
app/models/internal/VersionSetLookupResult.java
app/models/internal/VersionSpecification.java
app/models/internal/VersionSpecificationAttribute.java
app/models/internal/impl/DefaultPackageVersion.java
app/models/internal/impl/DefaultVersionSet.java
app/models/internal/impl/DefaultVersionSpecification.java
app/models/internal/impl/DefaultVersionSpecificationAttribute.java
app/models/view/PackageVersion.java
app/models/view/VersionSet.java
app/models/view/VersionSpecification.java
app/models/view/VersionSpecificationDetails.java

***Squash before merge***
Part of the Evergreen WIP: This PR introduces the controller, internal models and view models.
Remaining:
* Routes
* DB repository implementation of the new `VersionSpecificationRepository`

Evergreen controller

---

app/controllers/AlertController.java
app/controllers/ExpressionController.java
project/Build.scala

Upgrade to latest commons and other packages. Stop catching ConstraintsViolatedException when deserializing JSON with Jackson.

Latest Commons

---

app/controllers/ApplicationController.java
app/controllers/ProxyController.java
app/global/MainModule.java
app/models/internal/Features.java
app/models/internal/impl/DefaultFeatures.java
app/views/HeaderViewModel.scala.html
conf/portal.application.conf
conf/portal.routes
project/Build.scala
public/html/GraphViewModel.html

Added feature flags to control different aspects of the application: telemetry, hosts, expressions, alerts. Also added feature setting for telemetry to control proxy.

Feature Flags

---

app/com/arpnetworking/metrics/portal/health/DefaultHealthProvider.java
app/com/arpnetworking/metrics/portal/health/HealthProvider.java
app/controllers/MetaController.java
app/global/MainModule.java
conf/portal.application.conf

Refactor health check into configurable and injectable health provider interface and default implementation.
This addresses #76

Injectable Health Provider

---

app/com/arpnetworking/metrics/portal/alerts/impl/DatabaseAlertRepository.java
app/com/arpnetworking/metrics/portal/hosts/impl/DatabaseHostRepository.java
app/controllers/HostController.java
app/models/internal/Host.java
app/models/internal/Quantity.java
app/models/internal/impl/DefaultHost.java
app/models/internal/impl/DefaultQuantity.java
test/com/arpnetworking/metrics/portal/alerts/impl/DatabaseAlertRepositoryTest.java

** Strange: This fails a unit test on my host repeatedly. I cannot find the problem, and it passes in Travis. **

Switched from Guava Optional to Java Optional.

---

app/assets/javascripts/classes/ConnectionModel.ts
app/assets/javascripts/classes/HeaderViewModel.ts
app/assets/javascripts/classes/alerts/AlertsViewModel.ts
app/assets/javascripts/classes/expressions/ExpressionsViewModel.ts
app/assets/javascripts/classes/hostregistry/HostRegistryViewModel.ts
app/assets/javascripts/metrics_portal.ts
app/assets/javascripts/start_app.ts
public/html/index.html

I looked for other paths, but didn't find any.  Hopefully this is all of them.

use relative paths to allow for a path prefix

---

README.md
app/assets/javascripts/classes/GaugeVM.ts
app/assets/javascripts/classes/GraphVM.ts
app/assets/javascripts/classes/GraphViewModel.ts
app/assets/javascripts/classes/ReportData.ts
app/assets/javascripts/classes/StatisticView.ts
project/Build.scala

This is really basic plumbing of single unit metrics to the user interface.

Add basic units support.

---

app/assets/javascripts/classes/HeaderViewModel.ts
app/assets/javascripts/classes/KnockoutBindings.ts

fix the typeahead knockout binding
fix header use of typeahead

rework typeahead

---

project/Build.scala

disable rjs due to js version and cdn references
fix pid file
add universal plugin

Build fixes

---

app/assets/javascripts/classes/ConnectionModel.ts
app/assets/javascripts/libs/configure.d.ts
app/assets/javascripts/start_app.ts
app/controllers/ApplicationController.java
app/models/internal/Features.java
app/models/internal/impl/DefaultFeatures.java
app/views/ConfigureJsViewModel.scala.html
conf/portal.application.conf
conf/portal.routes
public/html/index.html

Plumb features configuration into javascript via templated js resource. Use the existing proxy feature to gate browser side proxying. Add a feature to configure potential metrics aggregator daemon ports.

Configurable MAD Ports

---

app/global/Global.java
app/global/PillarModule.java
conf/cluster.conf

Clean up the Cassandra shutdown as well as let Play shutdown the ActorSystem properly.  This addresses a race condition in shutdown and notification of cluster membership leaving that causes hangs in Travis.

make sure to shutdown cassandra sessions

---

project/Build.scala
test/com/arpnetworking/metrics/portal/alerts/impl/CassandraAlertRepositoryTest.java
test/com/arpnetworking/metrics/portal/alerts/impl/DatabaseAlertRepositoryTest.java
test/com/arpnetworking/metrics/portal/expressions/impl/DatabaseExpressionRepositoryTest.java
test/com/arpnetworking/metrics/portal/hosts/impl/CassandraHostRepositoryTest.java
test/com/arpnetworking/metrics/portal/hosts/impl/ConsulClientTest.java
test/com/arpnetworking/metrics/portal/hosts/impl/DatabaseHostRepositoryTest.java
test/com/arpnetworking/metrics/portal/hosts/impl/ElasticSearchHostRegistryTest.java
test/com/arpnetworking/metrics/portal/hosts/impl/ForemanClientTest.java
test/com/arpnetworking/metrics/portal/models/ebean/VersionSpecificationTest.java
test/com/arpnetworking/utility/ConfigTypedProviderTest.java
test/controllers/AlertControllerTest.java
test/controllers/ExpressionControllerTest.java

I also updated the tests to import statics for org.junit.Assert and Mockito.

Upgraded to latest build-resources which allows static imports in test files.

---

.gitignore
app/com/arpnetworking/metrics/portal/scheduling/JobCoordinator.java
app/com/arpnetworking/metrics/util/PagingIterator.java
app/global/MainModule.java
test/com/arpnetworking/metrics/portal/AkkaClusteringConfigFactory.java
test/com/arpnetworking/metrics/portal/scheduling/JobCoordinatorTest.java
test/com/arpnetworking/metrics/portal/scheduling/impl/MapJobRepository.java
test/com/arpnetworking/metrics/util/PagingIteratorTest.java
test/com/arpnetworking/metrics/util/package-info.java

Add a `JobCoordinator` actor, which performs anti-entropy on a `JobRepository`'s executor-actors.

Job coordinator

---

README.md
app/com/arpnetworking/metrics/portal/hosts/impl/ConfiguredHostProvider.java

Add a new configured host provider for hosts which cannot be discovered dynamically, but which are highly static.

Configured Host Provider

---

app/com/arpnetworking/metrics/portal/hosts/HostRepository.java
app/com/arpnetworking/metrics/portal/hosts/impl/CassandraHostRepository.java
app/com/arpnetworking/metrics/portal/hosts/impl/DatabaseHostRepository.java
app/com/arpnetworking/metrics/portal/hosts/impl/ElasticSearchHostRepository.java
app/com/arpnetworking/metrics/portal/hosts/impl/LocalHostRepository.java
app/com/arpnetworking/metrics/portal/hosts/impl/NoHostRepository.java
app/controllers/HostController.java
conf/portal.routes

Add host get and addOrUpdate API endpoints as well as repository implementations.

Host Endpoints

---

app/com/arpnetworking/metrics/portal/hosts/impl/DatabaseHostRepository.java

The current version of ebean parses the `order by` clause in SQL making the assumption that there are not `,` (commas) in the line other than those separating values to order by. In the case of PG full text search there are multi-argument function calls to compute the score.
Ref:
https://github.com/ebean-orm/ebean/blob/master/src/main/java/io/ebean/OrderBy.java#L412
This change moves the score computation for result ordering into a computed column and ignores that column on object mapping.

Fix postgresql host query with full text index.

---

app/controllers/KairosDbProxy.java
app/global/MainModule.java
conf/portal.application.conf
test/java/com/arpnetworking/metrics/portal/H2ConnectionStringFactory.java

also fix test issues and a @Nullable error

fix rollup singleton proxy

---

app/models/ebean/Alert.java
app/models/ebean/AlertEtags.java
app/models/ebean/ChromeScreenshotReportSource.java
app/models/ebean/Host.java
app/models/ebean/HtmlReportFormat.java
app/models/ebean/NagiosExtension.java
app/models/ebean/NeverReportSchedule.java
app/models/ebean/OneOffReportSchedule.java
app/models/ebean/Organization.java
app/models/ebean/PdfReportFormat.java
app/models/ebean/PeriodicReportSchedule.java
app/models/ebean/Recipient.java
app/models/ebean/Report.java
app/models/ebean/ReportExecution.java
app/models/ebean/ReportFormat.java
app/models/ebean/ReportRecipientAssoc.java
app/models/ebean/ReportSchedule.java
app/models/ebean/ReportSource.java

Add note to class header for all ebean classes to avoid functionality that serializes the class contents due to dangers of it initiating database access.

Ebean Model Serialization

---

app/com/arpnetworking/kairos/client/KairosDbRequestException.java
app/com/arpnetworking/rollups/RollupGenerator.java

Exception serialization into logs and add success metrics to message processing in roll-up actor.

Improve Rollup Visibility

---

app/com/arpnetworking/metrics/portal/scheduling/impl/PeriodicSchedule.java
app/models/view/impl/NeverSchedule.java
app/models/view/scheduling/Schedule.java

We already have internal/ebean classes for it. I opine that it should have a view model too, or we should delete the internal/ebean classes.

add view model for NeverSchedule

---

pom.xml
test/java/com/arpnetworking/metrics/portal/integration/test/EbeanServerHelper.java

Perform a Flyway migration on the portal schema when obtaining a reference to the Ebean server to allow repository integration tests to be run from IDE against a Postgresql instance w/o running an instance of the application.

Repository IT Migrate Flyway

---

conf/portal.application.conf
pom.xml
test/java/com/arpnetworking/metrics/portal/integration/controllers/KairosDbProxyControllerIT.java

Add inscopemetrics/kairosdb-extensions Docker image to Maven verification pass and simple integration test for the health check endpoint proxied through Metrics Portal.

KairosDb Docker

---

app/assets/javascripts/classes/reports/Models.ts
app/models/ebean/WebPageReportSource.java

Grafana reports currently aren't loaded correctly from JSON, so they can't be loaded properly in Edit mode.

fix UI editing of Grafana reports

---

app/com/arpnetworking/metrics/portal/reports/impl/chrome/DefaultDevToolsFactory.java
app/com/arpnetworking/metrics/portal/reports/impl/chrome/DevToolsService.java
app/com/arpnetworking/metrics/portal/reports/impl/chrome/DevToolsServiceWrapper.java
app/com/arpnetworking/metrics/portal/reports/impl/chrome/HtmlScreenshotRenderer.java
app/com/arpnetworking/metrics/portal/reports/impl/chrome/PdfScreenshotRenderer.java
app/com/arpnetworking/metrics/portal/reports/impl/chrome/grafana/BaseGrafanaScreenshotRenderer.java
app/com/arpnetworking/metrics/portal/reports/impl/chrome/grafana/HtmlGrafanaScreenshotRenderer.java
app/com/arpnetworking/metrics/portal/reports/impl/chrome/grafana/PdfGrafanaScreenshotRenderer.java
conf/portal.application.conf
test/java/com/arpnetworking/metrics/portal/reports/impl/chrome/BaseChromeTestSuite.java
test/java/com/arpnetworking/metrics/portal/reports/impl/chrome/DevToolsServiceWrapperTest.java
test/java/com/arpnetworking/metrics/portal/reports/impl/chrome/HtmlScreenshotRendererTest.java
test/java/com/arpnetworking/metrics/portal/reports/impl/chrome/PdfScreenshotRendererTest.java
test/java/com/arpnetworking/metrics/portal/reports/impl/chrome/grafana/HtmlScreenshotRendererTest.java
test/java/com/arpnetworking/metrics/portal/reports/impl/chrome/grafana/PdfScreenshotRendererTest.java

This diff is probably best viewed commit-by-commit.

Make Chrome devtools actions cancellable

---

.travis.yml

...and only import gpg key for Maven if deploying

bump Travis build environment to Ubuntu 18.04

---

app/com/arpnetworking/metrics/portal/query/QueryExecutionException.java
app/com/arpnetworking/metrics/portal/query/impl/NoQueryExecutor.java
app/com/arpnetworking/play/metrics/ProblemHelper.java
app/controllers/MetricsController.java
app/models/internal/Problem.java

...and refactor some associated methods out of MetricsController, so that they can eventually get reused for Reports.

generalize QueryProblem -> Problem

---

app/com/arpnetworking/metrics/portal/reports/impl/chrome/PerOriginConfigs.java
conf/portal.application.conf
test/java/com/arpnetworking/metrics/portal/reports/impl/chrome/PerOriginConfigsTest.java

It will now send email to anyone, and allow navigation/requests to any web page.

make default configuration very permissive

---

.travis.yml

make .travis.yml valid YAML

---

app/com/arpnetworking/kairos/service/KairosDbServiceImpl.java
test/java/com/arpnetworking/metrics/portal/integration/controllers/KairosDbProxyControllerIT.java

Removes filter tags based on configured excluded tags from query response unless explicitly requested in the metrics query. Next step is to evaluate what if anything needs to be done for group-by.

Add tag exclusions to query metrics and response.

---

app/com/arpnetworking/kairos/client/models/Metric.java
app/com/arpnetworking/kairos/client/models/MetricsQuery.java
app/com/arpnetworking/kairos/client/models/MetricsQueryResponse.java
app/com/arpnetworking/metrics/portal/health/ClusterStatusCacheActor.java
app/com/arpnetworking/metrics/portal/health/StatusActor.java
app/com/arpnetworking/rollups/RollupExecutor.java
app/models/internal/ShardAllocation.java
extra-checkstyle-suppressions.xml
pom.xml
settings.xml
test/java/com/arpnetworking/kairos/client/models/MetricTest.java
test/java/com/arpnetworking/kairos/client/models/MetricsQueryBinGroupByTest.java
test/java/com/arpnetworking/kairos/client/models/MetricsQueryResponseQueryBinGroupByTest.java
test/java/com/arpnetworking/kairos/client/models/MetricsQueryResponseQueryTimeGroupByTest.java
test/java/com/arpnetworking/kairos/client/models/MetricsQueryResponseQueryValueGroupByTest.java
test/java/com/arpnetworking/kairos/client/models/MetricsQueryTagGroupByTest.java
test/java/com/arpnetworking/kairos/client/models/MetricsQueryTimeGroupByTest.java
test/java/com/arpnetworking/kairos/client/models/MetricsQueryTypeGroupByTest.java
test/java/com/arpnetworking/kairos/client/models/MetricsQueryValueGroupByTest.java
test/java/com/arpnetworking/metrics/portal/integration/controllers/KairosDbProxyControllerIT.java
test/java/com/arpnetworking/rollups/RollupExecutorTest.java
test/resources/com/arpnetworking/kairos/client/models/MetricTest.testTranslationLosesNothing.json
test/resources/com/arpnetworking/kairos/client/models/MetricsQueryBinGroupByTest.testTranslationLosesNothing.json
test/resources/com/arpnetworking/kairos/client/models/MetricsQueryResponseQueryBinGroupByTest.testTranslationLosesNothing.json
test/resources/com/arpnetworking/kairos/client/models/MetricsQueryResponseQueryTimeGroupByTest.testTranslationLosesNothing.json
test/resources/com/arpnetworking/kairos/client/models/MetricsQueryResponseQueryValueGroupByTest.testTranslationLosesNothing.json
test/resources/com/arpnetworking/kairos/client/models/MetricsQueryTagGroupByTest.testTranslationLosesNothing.json
test/resources/com/arpnetworking/kairos/client/models/MetricsQueryTimeGroupByTest.testTranslationLosesNothing.json
test/resources/com/arpnetworking/kairos/client/models/MetricsQueryTypeGroupByTest.testTranslationLosesNothing.json
test/resources/com/arpnetworking/kairos/client/models/MetricsQueryValueGroupByTest.testTranslationLosesNothing.json

Complete data model for group by and add tests ensuring that tag filtering does not impact group by.

Filtering & Group By

---

public/html/components/Pager.html
public/stylesheets/main.css

There's probably a better way to do this, and I'll happily implement that instead if you tell me what it is.

add spacer below table so bottom row isn't hidden by navbar

---

app/global/ErrorHandler.java

We can see these in metrics, and somewhat infer from the stack traces but I'd rather be explicit here.

include the method, path, and status code for the ErrorHandler logs

---

app/com/arpnetworking/rollups/RollupExecutor.java
app/com/arpnetworking/rollups/RollupForwarder.java
app/com/arpnetworking/rollups/RollupGenerator.java

- consolidate logging of some success metrics
- fix/link some Javadocs

rollups: some nits

---

app/com/arpnetworking/rollups/RollupExecutor.java

(It's _also_ confusing that these two have the same name. I'll consider fixing that, or combining them into one class, in a later diff.)

fix reference to wrong class

---

app/com/arpnetworking/kairos/service/KairosDbServiceImpl.java
app/com/arpnetworking/rollups/RollupExecutor.java
app/com/arpnetworking/rollups/RollupGenerator.java
test/java/com/arpnetworking/rollups/RollupExecutorTest.java

This should make our logs somewhat quieter.

use ThreadLocalBuilder where possible

---

app/com/arpnetworking/metrics/portal/scheduling/JobExecutorActor.java

This is the time between when the job was scheduled vs. when it actually
executed. So for example, if a job was scheduled for `16:00:00` and runs at `16:00:42`, then the lag is 42 seconds.

Measure job execution lag

---

app/com/arpnetworking/metrics/portal/scheduling/JobCoordinator.java

The anti-entropy actor only makes sense for a particular coordinator, which is itself specific to a repository type. This breaks out those metrics into per-repository values, and adds a `job_count` metric to keep track of repo size increases over time.

emit anti-entropy metrics by repository type

---

app/com/arpnetworking/rollups/RollupManager.java
test/java/com/arpnetworking/rollups/RollupManagerTest.java

Purpose: explained by comment.

rollups: put a delay between writing a rollup and submitting a consistency-check request

---

app/com/arpnetworking/metrics/portal/query/impl/KairosDbQueryExecutor.java
app/com/arpnetworking/rollups/ConsistencyChecker.java
pom.xml
test/java/com/arpnetworking/metrics/portal/alerts/AlertExecutionContextTest.java
test/java/com/arpnetworking/testing/SerializationTestUtils.java

Example:
```
{"time":"2020-10-20T00:18:48.782Z","name":"log","level":"info","data":{"message":"Starting JVM metrics collector actor.","actor":"Actor[akka://mportal/user/$b#1451806056]"},"context":{"host":"localhost","processId":"1675","threadId":"mpor
tal-akka.actor.default-dispatcher-4","logger":"a.JvmMetricsCollector","line":"77","file":"JvmMetricsCollector.java","class":"actors.JvmMetricsCollector"},"id":"ba3a34c3-15f9-43d7-95c7-2996dac58ec7","version":"0"}
{"time":"2020-10-20T00:18:48.797Z","name":"EncodingException","level":"warn","data":{"originalMessage":null},"exception":{"type":"com.arpnetworking.logback.EncodingException","message":"Encoding Exception","backtrace":["com.arpnetworking.logback.StenoEncoder.buildListsMessage(StenoEncoder.java:805)","com.arpnetworking.logback.BaseLog …
```

Revert the Jackson upgrade from 2.9 to 2.10 as we are seeing serialization exceptions for log messages

---

app/com/arpnetworking/commons/tagger/MetricNameTagger.java
app/com/arpnetworking/commons/tagger/NoTagsTagger.java
app/com/arpnetworking/commons/tagger/Tagger.java
app/com/arpnetworking/commons/tagger/package-info.java
app/com/arpnetworking/rollups/RollupGenerator.java
app/global/MainModule.java
conf/portal.application.conf
test/java/com/arpnetworking/commons/tagger/MetricNameTaggerTest.java
test/java/com/arpnetworking/commons/tagger/package-info.java
test/java/com/arpnetworking/rollups/RollupGeneratorTest.java

Includes a basic tagger impl for extracting a prefix from the metric name.

add a metric for backfill age per period per namespace

---

app/com/arpnetworking/metrics/portal/alerts/impl/DailyPartitionCreator.java
app/com/arpnetworking/metrics/portal/scheduling/JobExecutorActor.java

There are some partition writing errors, and while it's unlikely these are caused by the job itself we don't know this for sure without logging to tie exception <-> jobRef

additional logging on job completion failure

---

.github/workflows/build.yml
.github/workflows/release.yml

See https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080 for details.

add workaround for Maven timeouts to Azure LBs

---

app/com/arpnetworking/metrics/portal/alerts/impl/AlertExecutionCacheActor.java

This was clearly incorrect, Jackson needs to either have an enclosing type with concrete parameters or use a type token in order to deserialize the ImmutableMap.
I'm not sure how this got past the test which [forces serialization during testing](https://github.com/cwbriones/metrics-portal/blob/79f368c4aef1640d74251591aee4f8c9c91d716d/test/java/com/arpnetworking/metrics/portal/alerts/impl/CachingAlertExecutionRepositoryTest.java#L77). I did the same during local testing but it seems that the only way to guarantee it's actual serializing the messages (since the config didn't work) is to actually run a local cluster.

wrap the responses so jackson understands the type parameters

---

app/com/arpnetworking/metrics/portal/scheduling/JobExecutorActor.java

When a future inside a Patterns.pipe completes exceptionally, we don't reset any of the internal actor state so it continues to think it's still executing. We should just restart the actor entirely to get back to a known good state.

job actor should be killed/restarted when a future fails

---

app/com/arpnetworking/metrics/portal/alerts/impl/AlertExecutionCacheActor.java

I have no idea why this worked while testing it.
In the staging environment I'm seeing a ClassCastException, since we're putting the wrong object into the cache.
```
java.util.LinkedHashMap cannot be cast to models.internal.alerts.AlertEvaluationResult
File "com/arpnetworking/metrics/portal/alerts/impl/AlertExecutionCacheActor.java", line 748, in copyJobExecution
File "com/arpnetworking/metrics/portal/alerts/impl/AlertExecutionCacheActor.java", line 274, in lambda$15
File "java/util/Optional.java", line 159, in ifPresent
...
```

snapshots should not use generics

---

app/com/arpnetworking/metrics/portal/alerts/AlertNotifier.java
app/com/arpnetworking/metrics/portal/alerts/impl/NopAlertNotifier.java
app/com/arpnetworking/metrics/portal/alerts/impl/SlackAlertNotifier.java
app/com/arpnetworking/metrics/portal/alerts/scheduling/AlertExecutionContext.java
app/global/MainModule.java
conf/portal.application.conf
test/java/com/arpnetworking/metrics/portal/alerts/AlertExecutionContextTest.java
test/java/com/arpnetworking/metrics/portal/alerts/impl/AlertJobRepositoryTest.java
test/java/com/arpnetworking/metrics/portal/alerts/impl/SlackAlertNotifierTest.java

starting work on an alerts notification mechanism

alerts notifier

---

app/com/arpnetworking/kairos/client/models/MetricsQuery.java
app/global/MainModule.java

Fixes an error where specifying an empty set of rollup origins causes an error on initialization

No rollup origins
